[package]
name = "shady-audio"
version = "0.1.0"
edition = "2021"
authors = ["TornaxO7 <tornax@pm.me>"]
description = "A high level library build upon cpal to retrieve audio for visualisation."
license = "GPL2"

[dependencies]
splines.workspace = true
cpal.workspace = true
realfft.workspace = true
tracing.workspace = true
ringbuffer = "0.15.0"
apodize = "1"
