[package]
name = "shady-audio"
version = "0.1.0"
edition = "2021"
authors = ["TornaxO7 <tornax@pm.me>"]
description = "A high level library build upon cpal to retrieve audio data which an be visualized."
license = "GPL2"

[dependencies]
cpal.workspace = true
realfft.workspace = true
tracing.workspace = true
