[package]
name = "shady-audio"
version = "0.1.0"
edition = "2021"
authors = ["TornaxO7 <tornax@pm.me>"]
description = "A high level library build upon cpal to retrieve audio for visualisation."
license = "GPLv3"
homepage = "https://github.com/TornaxO7/shady"
documentation = "https://docs.rs/shady-audio"
repository = "https://github.com/TornaxO7/shady"

[dependencies]
splines.workspace = true
cpal.workspace = true
realfft.workspace = true
tracing.workspace = true

ringbuffer = "0.15"
apodize = "1"
simple-easing = "1"
